### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by piperwelch** [anyaevostinar/SymbulationEmp#127]
The docs: 

- don't mention the cookiecutter Github things 
- don't mention R studio - add some guidance on installing R
- symbulation vs symbulation-default in simple repeat
- version of emdsk is wrong -- should be 1.38.48 
- don't need to cd into web, can use "make serve"
- collecting data has some issues 
- creating a new mode should be flushed out 
- library API index is malformed 
- Add guidance on how the plot generated by ggplot can be interpreted and the big takeaways from the papers so far
- Guide on the settings/things to try next/how to make more changes to them
- What the future/next steps are for code development, what we are hoping people might try adding
- pip3 instead of pip depending on setup

**Comment by anyaevostinar** [comment]
How are we doing on these?

**Comment by piperwelch** [comment]
Now that the symbulation logo is fixed, I'll do a pull request!
