### ISSUE TITLE
Change end_to_end tests to check approximate range of final values instead of exact match

### ISSUE THREAD

**Issue by anyaevostinar** [anyaevostinar/SymbulationEmp#35]
Specifically, making sure symbulation.cc is covered

**Comment by emilydolson** [comment]
Is anyone actively working on this or should I roll it into the PR I'm working on to add automated testing?

**Comment by anyaevostinar** [comment]
No one is working on it, I just wanted to make sure not to forget :) Are you adding more tests or just setting up GitHub actions? (both are good, I just had thought you were doing only github actions)

**Comment by emilydolson** [comment]
Awesome! So far I've just set up GitHub actions, but I want to make the tests actually pass before I submit the PR :). I may or may not write some additional tests.

**Comment by anyaevostinar** [comment]
Sounds good, they should all pass I think? Are they not?

**Comment by emilydolson** [comment]
They're not (on my computer at least), because of this exact issue (slight floating point variations between expected and actual).

**Comment by anyaevostinar** [comment]
Ah yes, the thing I was fearing would happen cross platform, I can make it a higher priority to do approximate range as well. Is it just slight differences, it's not a "random number generator being different" thing right?
