### ISSUE TITLE
Data file names automatically including Seed

### ISSUE THREAD

**Issue by acameron13** [anyaevostinar/SymbulationEmp#83]
Change the file name creation in symbulation.cc to automatically include the seed, rather than relying on the user to add the seed to the filename on the command line or in SymSettings

**Comment by anyaevostinar** [comment]
@emilydolson would this change mess up your workflow? It seems a good thing to do in the base software, but I don't want to surprise you.

**Comment by emilydolson** [comment]
No, it shouldn't mess anything up!
